service: recipe-backend

provider:
  name: aws
  region: ${env:AWS_REGION}
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    PINECONE_API_KEY: ${env:PINECONE_API_KEY}
  iam:
    role:
      statements:
        # DynamoDB
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${env:AWS_REGION}:*:table/recipe-jobs
        # ECR   
        - Effect: Allow
          Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:PutImage
            - ecr:InitiateLayerUpload
            - ecr:UploadLayerPart
            - ecr:CompleteLayerUpload
          Resource:
            - "*"

        - Effect: Allow
          Action:
            - ecr:CreateRepository
          Resource: "*"
  ecr:
    images:
      appimage:
        path: .

functions:
  app:
    image:
      name: appimage
    timeout: 30  # Max allowed by API Gateway
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

resources:
  Resources:
    RecipeJobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: recipe-jobs
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: job_id
            AttributeType: S
        KeySchema:
          - AttributeName: job_id
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: expires_at
          Enabled: true
